---

services:
  bookclub:
    container_name: bookclub
    image: ghcr.io/tsparr/hardcover_bookclub:latest
    restart: unless-stopped
    ports:
      - 8000:8000
    environment:
      - "DJANGO_SECRET_KEY=uXMhz0GYj2CWE0BBXwJy7W9bQQpMS019sFYRHGrFdsM="
      - "DJANGO_ALLOWED_HOSTS=bookclub.zmthree.xyz,localhost,127.0.0.1"
      - DJANGO_SETTINGS_MODULE=hardcover_bookclub.settings
      - DJANGO_ADMIN_USERNAME=admin
      - DJANGO_ADMIN_EMAIL=admin@email.com
      - DJANGO_ADMIN_PASSWORD=admin
      - DJANGO_CSRF_TRUSTED_ORIGINS=https://bookclub.zmthree.xyz
      - DJANGO_DEBUG=True
    # volumes:
    #   - "app-config:/config"
    #   - "temp-storage:/data"
