# Generated by Django 5.1.7 on 2025-03-24 03:46

import django.db.models.deletion
import django_cryptography.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BookGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("is_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "admins",
                    models.ManyToManyField(
                        related_name="administered_groups", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        related_name="book_groups", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("author", models.CharField(max_length=200)),
                ("hardcover_id", models.CharField(max_length=50, unique=True)),
                ("cover_image_url", models.URLField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("pages", models.IntegerField(blank=True, null=True)),
                ("audio_seconds", models.IntegerField(blank=True, null=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to="bookclub.bookgroup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "progress_type",
                    models.CharField(
                        choices=[
                            ("page", "Page Number"),
                            ("audio", "Audio Timestamp"),
                            ("percent", "Percentage"),
                        ],
                        max_length=10,
                    ),
                ),
                ("progress_value", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("hardcover_started_at", models.DateTimeField(blank=True, null=True)),
                ("hardcover_finished_at", models.DateTimeField(blank=True, null=True)),
                ("hardcover_percent", models.FloatField(blank=True, null=True)),
                ("hardcover_current_page", models.IntegerField(blank=True, null=True)),
                (
                    "hardcover_current_position",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "hardcover_reading_format",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "hardcover_edition_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="bookclub.book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hardcover_api_key",
                    django_cryptography.fields.encrypt(
                        models.TextField(blank=True, null=True)
                    ),
                ),
                ("can_create_groups", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserBookProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "progress_type",
                    models.CharField(
                        choices=[
                            ("page", "Page Number"),
                            ("audio", "Audio Timestamp"),
                            ("percent", "Percentage"),
                        ],
                        max_length=10,
                    ),
                ),
                ("progress_value", models.CharField(max_length=20)),
                ("normalized_progress", models.FloatField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("hardcover_started_at", models.DateTimeField(blank=True, null=True)),
                ("hardcover_finished_at", models.DateTimeField(blank=True, null=True)),
                ("hardcover_percent", models.FloatField(blank=True, null=True)),
                ("hardcover_current_page", models.IntegerField(blank=True, null=True)),
                (
                    "hardcover_current_position",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "hardcover_reading_format",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "hardcover_edition_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_progress",
                        to="bookclub.book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "book")},
            },
        ),
    ]
