# Generated by Django 5.1.7 on 2025-03-24 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookclub", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookEdition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hardcover_edition_id", models.CharField(max_length=50, unique=True)),
                ("title", models.CharField(max_length=300)),
                ("isbn", models.CharField(blank=True, max_length=20, null=True)),
                ("isbn13", models.CharField(blank=True, max_length=20, null=True)),
                ("cover_image_url", models.URLField(blank=True)),
                ("publisher", models.CharField(blank=True, max_length=200)),
                ("publication_date", models.DateField(blank=True, null=True)),
                ("pages", models.IntegerField(blank=True, null=True)),
                ("audio_seconds", models.IntegerField(blank=True, null=True)),
                ("reading_format", models.CharField(blank=True, max_length=20)),
                ("reading_format_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="editions",
                        to="bookclub.book",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="userbookprogress",
            name="edition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_progress",
                to="bookclub.bookedition",
            ),
        ),
    ]
