# Generated by Django 5.1.7 on 2025-03-23 21:13

import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookclub", "0002_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="hardcover_api_key",
            field=django_cryptography.fields.encrypt(
                models.TextField(blank=True, null=True)
            ),
        ),
    ]
