# Generated by Django 5.1.7 on 2025-03-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookclub", "0002_bookedition_userbookprogress_edition"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
