# Generated by Django 5.1.7 on 2025-03-24 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookclub", "0004_book_audio_seconds_book_pages_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserBookProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "progress_type",
                    models.CharField(
                        choices=[
                            ("page", "Page Number"),
                            ("audio", "Audio Timestamp"),
                            ("percent", "Percentage"),
                        ],
                        max_length=10,
                    ),
                ),
                ("progress_value", models.CharField(max_length=20)),
                ("normalized_progress", models.FloatField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("hardcover_started_at", models.DateTimeField(blank=True, null=True)),
                ("hardcover_finished_at", models.DateTimeField(blank=True, null=True)),
                ("hardcover_percent", models.FloatField(blank=True, null=True)),
                ("hardcover_current_page", models.IntegerField(blank=True, null=True)),
                (
                    "hardcover_current_position",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "hardcover_reading_format",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "hardcover_edition_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_progress",
                        to="bookclub.book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "book")},
            },
        ),
    ]
