# Generated by Django 5.1.7 on 2025-03-25 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookclub", "0004_comment_parent_commentreaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="url",
            field=models.URLField(blank=True),
        ),
    ]
