# Generated by Django 5.1.7 on 2025-03-27 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookclub", "0007_userbookprogress_hardcover_read_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"ordering": ["display_order", "id"]},
        ),
        migrations.AddField(
            model_name="book",
            name="display_order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="book",
            name="is_collective_pick",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="book",
            name="picked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="book_picks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
