# Generated by Django 5.1.7 on 2025-03-27 14:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookclub", "0008_alter_book_options_book_display_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userbookprogress",
            name="hardcover_rating",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=2,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
