# Generated by Django 5.1.7 on 2025-03-31 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookclub", "0009_userbookprogress_hardcover_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="kavita_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="kavita_url",
            field=models.URLField(blank=True),
        ),
    ]
