# Generated by Django 5.1.7 on 2025-03-31 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookclub", "0010_book_kavita_id_book_kavita_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="kavita_id",
        ),
    ]
