# Generated by Django 5.1.7 on 2025-03-31 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookclub", "0011_remove_book_kavita_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="plex_url",
            field=models.URLField(blank=True),
        ),
    ]
