# Generated by Django 5.1.7 on 2025-04-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookclub", "0012_book_plex_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookedition",
            name="is_kavita_promoted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bookedition",
            name="is_plex_promoted",
            field=models.BooleanField(default=False),
        ),
    ]
