# Generated by Django 5.1.7 on 2025-04-02 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookclub", "0013_bookedition_is_kavita_promoted_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberStartingPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bookclub.bookgroup",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "set_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="set_starting_points",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "starting_book",
                    models.ForeignKey(
                        help_text="The first book this member was eligible to pick",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bookclub.book",
                    ),
                ),
            ],
            options={
                "ordering": ["group", "starting_book__display_order"],
                "unique_together": {("group", "member")},
            },
        ),
    ]
