# Generated by Django 5.1.8 on 2025-04-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookclub", "0016_bookgroup_enable_dollar_bets_dollarbet"),
    ]

    operations = [
        migrations.AddField(
            model_name="dollarbet",
            name="spoiler_level",
            field=models.CharField(
                choices=[
                    ("none", "No Spoilers"),
                    ("halfway", "Halfway Through Book"),
                    ("finished", "Finished Book"),
                ],
                default="halfway",
                help_text="When should this bet be visible to readers?",
                max_length=10,
            ),
        ),
    ]
