# Generated by Django 5.1.8 on 2025-04-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookclub", "0017_dollarbet_spoiler_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dollarbet",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("accepted", "Accepted"),
                    ("won", "Won"),
                    ("lost", "Lost"),
                    ("inconclusive", "Inconclusive"),
                ],
                default="open",
                max_length=12,
            ),
        ),
    ]
