# Generated by Django 5.1.8 on 2025-04-08 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookclub", "0019_userprofile_enable_notifications_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="notification_preferences",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="User's notification preferences for different types of notifications",
            ),
        ),
    ]
