# Generated by Django 5.1.8 on 2025-04-10 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookclub", "0021_add_dollar_bet_notification_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="dollarbet",
            name="counter_description",
            field=models.TextField(
                blank=True,
                help_text="The accepter's alternative prediction (e.g., 'No, Character Y will die instead')",
                null=True,
            ),
        ),
    ]
