# Generated by Django 5.1.8 on 2025-11-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookclub", "0022_dollarbet_counter_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentreaction",
            name="reaction",
            field=models.CharField(
                choices=[
                    ("👍", "Thumbs Up"),
                    ("❤️", "Heart"),
                    ("😂", "Laugh"),
                    ("😮", "Wow"),
                    ("😢", "Sad"),
                    ("🎉", "Celebrate"),
                    ("💡", "Idea"),
                    ("📚", "Book"),
                    ("☠️", "Skull and Crossbones"),
                    ("👻", "Ghost"),
                    ("💩", "Hankey"),
                    ("👽", "Alien"),
                    ("🧑\u200d🦼", "Person in Motorized Wheelchair"),
                    ("🧑\u200d🦯", "Person with Probing Cane"),
                    ("✨", "Sparkles"),
                ],
                max_length=10,
            ),
        ),
    ]
