# Generated by Django 5.1.2 on 2026-01-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookclub", "0023_alter_commentreaction_reaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="home_page_preference",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="User's home page preference: type (default/group/active_book) and group_id",
            ),
        ),
    ]
