# Generated by Django 5.1.15 on 2026-01-28 23:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0024_meeting_meetingattendance_meeting_members_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ['start_time', 'id']},
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['group', 'book', 'meeting_number'], name='bookclub_me_group_i_59774d_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['group', 'start_time'], name='bookclub_me_group_i_4b64c0_idx'),
        ),
    ]
