# Generated by Django 5.1.15 on 2026-01-30 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0026_remove_is_public_and_update_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
