# Generated by Django 5.1.8 on 2026-03-16 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookclub", "0024_userprofile_home_page_preference"),
        ("bookclub", "0028_bookgroup_enable_meetings"),
    ]

    operations = []
