# Generated by Django 5.1.8 on 2026-03-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookclub", "0029_merge_20260316_2029"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookgroup",
            name="enable_meetings",
            field=models.BooleanField(
                default=False, help_text="Enable Meetings in this group"
            ),
        ),
    ]
