# Generated by Django 5.1.8 on 2026-04-28 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookclub", "0030_change_enable_meetings_default"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bookgroup",
            name="enable_book_proposals",
            field=models.BooleanField(
                default=False,
                help_text="Allow members to propose books for group consideration",
            ),
        ),
        migrations.CreateModel(
            name="BookProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hardcover_id", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=300)),
                ("author", models.CharField(max_length=200)),
                ("cover_image_url", models.URLField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("url", models.URLField(blank=True)),
                ("pages", models.IntegerField(blank=True, null=True)),
                ("audio_seconds", models.IntegerField(blank=True, null=True)),
                (
                    "proposal_note",
                    models.TextField(
                        blank=True,
                        help_text="Optional note from proposer about why they suggest this book",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                (
                    "created_book",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_proposal",
                        to="bookclub.book",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book_proposals",
                        to="bookclub.bookgroup",
                    ),
                ),
                (
                    "proposed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book_proposals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_proposals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("group", "hardcover_id", "status")},
            },
        ),
    ]
