# Generated by Django 5.1.8 on 2026-05-14 15:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookclub", "0031_bookgroup_enable_book_proposals_bookproposal"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dollarbet",
            name="bet_type",
            field=models.CharField(
                choices=[("two_party", "Two Party"), ("multi_party", "Multi Party")],
                default="two_party",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="dollarbet",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created the bet",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_bets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dollarbet",
            name="max_participants",
            field=models.IntegerField(
                blank=True,
                help_text="Maximum participants allowed (multi-party only, optional)",
                null=True,
                validators=[django.core.validators.MinValueValidator(2)],
            ),
        ),
        migrations.AddField(
            model_name="dollarbet",
            name="min_participants",
            field=models.IntegerField(
                default=2,
                help_text="Minimum participants required (multi-party only)",
                validators=[django.core.validators.MinValueValidator(2)],
            ),
        ),
        migrations.AddField(
            model_name="dollarbet",
            name="question",
            field=models.TextField(
                blank=True,
                help_text="The question being bet on (multi-party only)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="dollarbet",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="What the bet is about (two-party only)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="dollarbet",
            name="proposer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proposed_dollar_bets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="dollarbet",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("accepted", "Accepted"),
                    ("active", "Active"),
                    ("won", "Won"),
                    ("lost", "Lost"),
                    ("resolved_winner", "Resolved - Winner"),
                    ("inconclusive", "Inconclusive"),
                    ("resolved_inconclusive", "Resolved - Inconclusive"),
                ],
                default="open",
                max_length=25,
            ),
        ),
        migrations.CreateModel(
            name="BetParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prediction",
                    models.TextField(
                        help_text="This participant's prediction/answer to the bet question"
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="bookclub.dollarbet",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bet_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["joined_at"],
                "unique_together": {("bet", "user")},
            },
        ),
    ]
