# Generated by Django 5.1.8 on 2026-05-14 15:10

from django.db import migrations


def populate_creator(apps, schema_editor):
    """Populate creator field for existing bets from proposer"""
    DollarBet = apps.get_model("bookclub", "DollarBet")
    for bet in DollarBet.objects.all():
        # For legacy two-party bets, proposer is the creator
        bet.creator = bet.proposer
        bet.save()


def reverse_populate_creator(apps, schema_editor):
    """Reverse migration - clear creator field"""
    DollarBet = apps.get_model("bookclub", "DollarBet")
    DollarBet.objects.all().update(creator=None)


class Migration(migrations.Migration):

    dependencies = [
        ("bookclub", "0032_multi_party_bets_model"),
    ]

    operations = [
        migrations.RunPython(populate_creator, reverse_populate_creator),
    ]
