# Generated by Django 5.1.8 on 2026-05-14 15:10

from django.db import migrations


def migrate_status_values(apps, schema_editor):
    """Migrate old status values to new system"""
    DollarBet = apps.get_model("bookclub", "DollarBet")

    # accepted → active
    DollarBet.objects.filter(status="accepted").update(status="active")

    # won/lost → resolved_winner (winner field already indicates who won)
    DollarBet.objects.filter(status__in=["won", "lost"]).update(
        status="resolved_winner"
    )

    # inconclusive → resolved_inconclusive
    DollarBet.objects.filter(status="inconclusive").update(
        status="resolved_inconclusive"
    )


def reverse_migrate_status_values(apps, schema_editor):
    """Reverse migration - restore old status values"""
    DollarBet = apps.get_model("bookclub", "DollarBet")

    # active → accepted
    DollarBet.objects.filter(status="active").update(status="accepted")

    # resolved_winner → won (can't perfectly reverse, but use won as default)
    DollarBet.objects.filter(status="resolved_winner").update(status="won")

    # resolved_inconclusive → inconclusive
    DollarBet.objects.filter(status="resolved_inconclusive").update(
        status="inconclusive"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("bookclub", "0033_populate_creator_field"),
    ]

    operations = [
        migrations.RunPython(migrate_status_values, reverse_migrate_status_values),
    ]
