# Generated by Django 5.1.8 on 2026-05-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookclub", "0034_migrate_status_values"),
    ]

    operations = [
        migrations.AddField(
            model_name="betparticipant",
            name="is_winner",
            field=models.BooleanField(
                default=False,
                help_text="True if this participant won the bet (supports multiple winners)",
            ),
        ),
    ]
