# Generated by Django 5.1.8 on 2026-05-14 16:57

from django.db import migrations


def sync_is_winner_flags(apps, schema_editor):
    """
    Sync is_winner flags for existing resolved multi-party bets.

    For multi-party bets with status='resolved_winner', if the DollarBet.winner
    field is set but no participants have is_winner=True, mark the winner's
    participant record as is_winner=True.
    """
    DollarBet = apps.get_model("bookclub", "DollarBet")
    BetParticipant = apps.get_model("bookclub", "BetParticipant")

    # Find all resolved multi-party bets
    multi_party_bets = DollarBet.objects.filter(
        bet_type="multi_party", status="resolved_winner"
    )

    synced_count = 0
    for bet in multi_party_bets:
        if not bet.winner_id:
            continue

        # Check if any participants are already marked as winners
        existing_winners = BetParticipant.objects.filter(
            bet=bet, is_winner=True
        ).count()

        # If no participants are marked but DollarBet.winner is set, sync it
        if existing_winners == 0:
            winner_participant = BetParticipant.objects.filter(
                bet=bet, user_id=bet.winner_id
            ).first()

            if winner_participant:
                winner_participant.is_winner = True
                winner_participant.save()
                synced_count += 1

    if synced_count > 0:
        print(f"Synced {synced_count} winner flags for multi-party bets")


def reverse_sync(apps, schema_editor):
    """Reverse migration - clear all is_winner flags"""
    BetParticipant = apps.get_model("bookclub", "BetParticipant")
    BetParticipant.objects.filter(is_winner=True).update(is_winner=False)


class Migration(migrations.Migration):

    dependencies = [
        ("bookclub", "0035_add_is_winner_to_bet_participant"),
    ]

    operations = [
        migrations.RunPython(sync_is_winner_flags, reverse_sync),
    ]
