name: Build Docker image
on:
  push:
    branches:
      - docker

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and tag image
        run: |
          export VERSION=$(cat VERSION)
          echo "Version: $VERSION" 
          docker build -t ${{ github.repository }}:$VERSION -f Dockerfile .

      - name: Push image to GHCR
        run: |
          export VERSION=$(cat VERSION)
          docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:$VERSION