name: Build Docker image
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to ghcr.io
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and tag image
        run: |
          export VERSION=$(cat VERSION)
          echo "Version: $VERSION" 
          docker build -t ${{ github.repository }}:$VERSION -f /Docker/Dockerfile .

      - name: Push image to GHCR
        run: |
          export VERSION=$(cat VERSION)
          docker tag ${{ github.repository }}:$VERSION ghcr.io/tsparr/hardcover_bookclub:$VERSION
          docker push ghcr.io/tsparr/hardcover_bookclub:$VERSION