name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - develop
    paths:
      - "Docker/**"
      - "VERSION"
      - ".github/workflows/docker-build.yml"
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Extract version
        id: version
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: Convert repository name to lowercase
        id: repo_name
        run: echo "REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
        
      - name: Set Docker tags
        id: set_tags
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "TAGS=ghcr.io/${{ env.REPO_NAME }}:${{ env.VERSION }},ghcr.io/${{ env.REPO_NAME }}:latest" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            echo "TAGS=ghcr.io/${{ env.REPO_NAME }}:${{ env.VERSION }}-dev,ghcr.io/${{ env.REPO_NAME }}:nightly" >> $GITHUB_ENV
          else
            echo "TAGS=ghcr.io/${{ env.REPO_NAME }}:${{ github.sha }}" >> $GITHUB_ENV
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Docker/Dockerfile
          push: true
          tags: ${{ env.TAGS }}
          cache-from: type=gha
          cache-to: type=gha,mode=max